# Generated by Django 4.0.1 on 2022-12-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('1', 'News'), ('2', 'Event'), ('3', 'Research-related'), ('4', 'Extension-related')], default='1', max_length=9),
        ),
    ]
