# Generated by Django 4.1.3 on 2022-12-11 01:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_admin_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile_img.jpg', null=True, upload_to=accounts.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'Research Coordinator'), ('3', 'Extension Coordinator'), ('4', 'Department Head'), ('5', 'Faculty')], default='5', max_length=9),
        ),
    ]
