# Generated by Django 4.1.3 on 2022-12-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_alter_department_head'),
        ('accounts', '0007_remove_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='department.department'),
        ),
    ]
