# Generated by Django 4.1.3 on 2022-12-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
